name: Run tests

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 0 */4 * * *

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install
      run: npm ci

    - name: Run tests
      run: npm run test
